;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Ability.Attack",DevComment="")
GameplayTagList=(Tag="Ability.Deffend",DevComment="")
GameplayTagList=(Tag="Ability.Melee",DevComment="")
GameplayTagList=(Tag="Ability.TurnToActor",DevComment="")
GameplayTagList=(Tag="Ability.TurnToActor.Cancel",DevComment="")
GameplayTagList=(Tag="Features.Melee.Attack.Mid",DevComment="")
GameplayTagList=(Tag="GameplayEvent.Character.Melee.Attack",DevComment="")
GameplayTagList=(Tag="GameplayEvent.Character.Melee.Deffend",DevComment="")
GameplayTagList=(Tag="GameplayEvent.Character.Melee.Trace",DevComment="")
GameplayTagList=(Tag="GameplayEvent.Character.Melee.Trace.End",DevComment="")
GameplayTagList=(Tag="GameplayEvent.Character.Melee.Trace.Start",DevComment="")

